export const FETCH_SCHEDULES_REQUESTED = 'FETCH_SCHEDULES_REQUESTED';
export const FETCH_SCHEDULES_SUCCEEDED = 'FETCH_SCHEDULES_SUCCEEDED';
export const FETCH_SCHEDULES_FAILED = 'FETCH_SCHEDULES_FAILED';

export const fetchSchedulesRequested = () => ({type: FETCH_SCHEDULES_REQUESTED })